# Generated by Django 4.2.3 on 2024-10-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetable_delete_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='available_days',
            field=models.JSONField(default=list),
        ),
    ]
